#!/bin/bash
  echo -e "Encontrar archivos por contenido\ngrep -rn "Linux" ~/*.txt"
  echo -e "alias limpia_log='rm ~/*.log; echo 'Logs eliminados'"
  echo -e '18. find + grep\ngrep -rl "Ubuntu" ~ --include="*.txt'
  echo "-lscpu es info del sistema"
  echo "sort ordenar"
echo "
